FA.JustBlog/FA.JustBlog/FA.JustBlog/Areas/Admin/Controllers/CategoryController.cs
using FA.JustBlog.Core.Models;
using FA.JustBlog.Core.Models.ViewModels;
using FA.JustBlog.Core.Repository;
using FA.JustBlog.Core.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Text;

namespace FA.JustBlog.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin, Contributor")]
    public class CategoryController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        IEnumerable<Category> CategoryList;

        public CategoryController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        
        public IActionResult Index()
        {
            CategoryList = _unitOfWork.Category.GetAll();
            return View(CategoryList);
        }

        //Create
        //Get
       
        public IActionResult Create()
        {
            Category newCategory = new Category();

            return View(newCategory);
        }

        //Post
        [HttpPost]
        [ValidateAntiForgeryToken]

        public IActionResult Create(Category category)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.Category.Add(category);
                _unitOfWork.Save();

                return RedirectToAction("Index");
            }
            return View(category);
        }

        //Update
        //Get
        public IActionResult Update(int? id)
        {
            if (id == null || id == 0)
                return NotFound();

            var category = _unitOfWork.Category.GetFirstOrDefault(x => x.Id == id);

            return View(category);
        }

        //Post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(Category category)
        {
            if (ModelState.IsValid)
            {
                //Update Tag
                _unitOfWork.Category.Update(category);
                _unitOfWork.Save();

                return RedirectToAction("Index");
            }
            return View(category);
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Delete(int? id)
        {
            if (id == null)
                return NotFound();

            var post = _unitOfWork.Post.GetFirstOrDefault(p => p.Id == id);
            _unitOfWork.Post.Delete(post);

            _unitOfWork.Save();
            return RedirectToAction("Index");
        }
    }
}

FA.JustBlog/FA.JustBlog/FA.JustBlog/Areas/Admin/Controllers/PostController.cs
using FA.JustBlog.Core.Models;
using FA.JustBlog.Core.Models.ViewModels;
using FA.JustBlog.Core.Repository;
using FA.JustBlog.Core.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Text;
using X.PagedList;

namespace FA.JustBlog.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin, Contributor")]
    public class PostController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        IEnumerable<Post> postList;
        public PostController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        
        public IActionResult Index(int? page = null, int? pageSize = null)
        {
            if (page == null)
                page = 1;

            if (pageSize == null)
                pageSize = 5;

            IList<PostVM> postVMs = new List<PostVM>();

            postList = _unitOfWork.Post.GetAll();
            foreach (var post in postList)
            {
                postVMs.Add(new PostVM()
                {
                    Post = post,
                    TimeSpan = Helper.TimeCompare(post.PostedOn)
                });
            }

            return View(postVMs.ToPagedList((int)page, (int)pageSize));
        }

        //Create
        //Get
       
        public IActionResult Create()
        {
            PostVM postVM = new()
            {
                Post = new(),
                CategoryList = _unitOfWork.Category.GetAll().Select(i => new SelectListItem
                {
                    Text = i.Name,
                    Value = i.Id.ToString()
                }),
                TagList = _unitOfWork.Tag.GetAll().ToList()

            };
            
            return View(postVM);
        }

        //Post
        [HttpPost]
        [ValidateAntiForgeryToken]

        public IActionResult Create(PostVM obj)
        {
            if (ModelState.IsValid)
            {
                //Set Published
                obj.Post.Published = false;
                if (obj.Published == "true")
                    obj.Post.Published = true;
                
                //Set UrlSlug
                var stringArr = obj.Post.Title.Split(' ');
                var urlSlug = new StringBuilder();
                foreach (var i in stringArr)
                {
                    urlSlug.Append("-"+i);
                }
                
                obj.Post.UrlSlug = SeoUrlHepler.FrientlyUrl(obj.Post.Title);

                _unitOfWork.Post.Add(obj.Post);
                _unitOfWork.Save();


                var lastPost = _unitOfWork.Post.GetAll().OrderByDescending(p => p.Id).FirstOrDefault();
                if(lastPost != null)
                {
                    //add new record to PostTagMap table
                    foreach (var tagName in obj.SelectedTag)
                    {
                        var tag = _unitOfWork.Tag.GetFirstOrDefault(t => t.Name == tagName);
                        if (tag != null)
                        {
                            var postTagMap = new PostTagMap()
                            {
                                PostId = lastPost.Id,
                                TagId = tag.Id
                            };

                            _unitOfWork.PostTagMap.Add(postTagMap);

                        }
                    }
                }
                

                //Add new Post
                
                _unitOfWork.Save();

                return RedirectToAction("Index");
            }
            return View(obj);
        }

        //Update
        //Get
        public IActionResult Update(int? id)
        {
            if (id == null || id == 0)      
                return NotFound();

            PostVM postVM = new()
            {
                Post = _unitOfWork.Post.GetFirstOrDefault(p => p.Id == id),
                CategoryList = _unitOfWork.Category.GetAll().Select(i => new SelectListItem
                {
                    Text = i.Name,
                    Value = i.Id.ToString()
                }),
                TagList = _unitOfWork.Tag.GetAll().ToList()

            };

            return View(postVM);
        }

        //Post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(PostVM obj)
        {
            if (ModelState.IsValid)
            {
                //Set Published
                obj.Post.Published = false;
                if (obj.Published == "true")
                    obj.Post.Published = true;

                //Set Modified 
                obj.Post.Modified = DateTime.Now;

                //update PostTagMap table
            
                List<PostTagMap> postTagMapFomrDb = _unitOfWork.PostTagMap.GetAll(t => t.PostId == obj.Post.Id).ToList();
                //Delete Old PostTagMap
                for (var i = 0; i < postTagMapFomrDb.Count(); i++)
                {
                    _unitOfWork.PostTagMap.Delete(postTagMapFomrDb[i]);
                }
                _unitOfWork.Save();

                //Add new Post Tag Map
                foreach (var tagName in obj.SelectedTag)
                {
                    var tag = _unitOfWork.Tag.GetFirstOrDefault(t => t.Name == tagName);
                    if (tag != null)
                    {
                        var postTagMap = new PostTagMap()
                        {
                            PostId = obj.Post.Id,
                            TagId = tag.Id
                        };

                        _unitOfWork.PostTagMap.Add(postTagMap);

                    }
                }

                //Update Post
                _unitOfWork.Post.Update(obj.Post);

                _unitOfWork.Save();

                return RedirectToAction("Index");
            }
            return View(obj);
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Delete(int? id)
        {
            if (id == null)
                return NotFound();

            var post = _unitOfWork.Post.GetFirstOrDefault(p => p.Id == id);
            _unitOfWork.Post.Delete(post);

            _unitOfWork.Save();
            return RedirectToAction("Index");
        }
    }
}

FA.JustBlog/FA.JustBlog/FA.JustBlog/Areas/Admin/Controllers/TagController.cs
using FA.JustBlog.Core.Models;
using FA.JustBlog.Core.Models.ViewModels;
using FA.JustBlog.Core.Repository;
using FA.JustBlog.Core.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Text;

namespace FA.JustBlog.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin, Contributor")]
    public class TagController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public TagController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        
        public IActionResult Index()
        {
            IEnumerable<Tag> Tags = new List<Tag>();

            Tags = _unitOfWork.Tag.GetAll();

            return View(Tags);
        }

        //Create
        //Get
  
        public IActionResult Create()
        {
            Tag newTag = new Tag();
            
            return View(newTag);
        }

        //Post
        [HttpPost]
        [ValidateAntiForgeryToken]

        public IActionResult Create(Tag tag)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.Tag.Add(tag);
                _unitOfWork.Save();

                return RedirectToAction("Index");
            }
            return View(tag);
        }

        //Update
        //Get
        public IActionResult Update(int? id)
        {
            if (id == null || id == 0)      
                return NotFound();

            var tag = _unitOfWork.Tag.GetFirstOrDefault(x => x.Id == id);

            return View(tag);
        }

        //Post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(Tag tag)
        {
            if (ModelState.IsValid)
            {
                //Update Tag
                _unitOfWork.Tag.Update(tag);
                _unitOfWork.Save();

                return RedirectToAction("Index");
            }
            return View(tag);
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Delete(int? id)
        {
            if (id == null)
                return NotFound();

            var tag = _unitOfWork.Tag.GetFirstOrDefault(p => p.Id == id);
            _unitOfWork.Tag.Delete(tag);

            _unitOfWork.Save();
            return RedirectToAction("Index");
        }
    }
}

FA.JustBlog/FA.JustBlog/FA.JustBlog/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FA.JustBlog</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/AdminStyle.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FA.JustBlog.styles.css" asp-append-version="true" />
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
    <link href="https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css" rel="stylesheet" />
    
    <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
</head>
<body class="sb-nav-fixed">
   <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
            <!-- Navbar Brand-->
            <a class="navbar-brand ps-3" href="index.html">Just Blog Admin Area</a>
            <!-- Sidebar Toggle-->
           
            <!-- Navbar Search-->
            <form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
                <div class="input-group">
                    <input class="form-control" type="text" placeholder="Search for..." aria-label="Search for..." aria-describedby="btnNavbarSearch" />
                    <button class="btn btn-primary" id="btnNavbarSearch" type="button"><i class="fas fa-search"></i></button>
                </div>
            </form>
            <!-- Navbar-->
            <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
               <li><a class="dropdown-item" style="color:azure;"
                   asp-area="Identity" asp-page="/Account/Logout" >Logout</a>
            </ul>
        </nav>
        <div id="layoutSidenav">
            <div id="layoutSidenav_nav">
                <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                    <div class="sb-sidenav-menu">
                        <div class="nav">
                            <div class="sb-sidenav-menu-heading">Core</div>
                            <a class="nav-link" asp-area="Customer" asp-controller="Post" asp-action="Index">  
                                <i class="fas fa-table"></i> &nbsp; Go to Home Page
                            </a>
                            <a class="nav-link" asp-area="Admin" asp-controller="Post" asp-action="Index">          
                                <i class="fas fa-book-open"></i> &nbsp; Post manage
                            </a>
                            <a class="nav-link" asp-area="Admin" asp-controller="Category" asp-action="Index">          
                                <i class="fas fa-book-open"></i> &nbsp; Category manage
                            </a>
                            <a class="nav-link" asp-area="Admin" asp-controller="Tag" asp-action="Index">          
                                <i class="fas fa-book-open"></i> &nbsp; Tag manage
                            </a>
                                                        
                            <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                                <nav class="sb-sidenav-menu-nested nav">
                                    <a class="nav-link" href="layout-static.html">Static Navigation</a>
                                    <a class="nav-link" href="layout-sidenav-light.html">Light Sidenav</a>
                                </nav>
                            </div>
                           
                            
                        </div>
                    </div>
                    <div class="sb-sidenav-footer">
                        <div class="small">Logged in as:</div>
                        Start Bootstrap
                    </div>
                </nav>
            </div>
            <div id="layoutSidenav_content">
                <div class="container">
                    <main role="main" class="pb-3">
                        @RenderBody()
                    </main>
                </div>
            </div>
        

 
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid px-4">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; Your Website 2022</div>
                    <div>
                        <a href="#">Privacy Policy</a>
                        &middot;
                        <a href="#">Terms &amp; Conditions</a>
                    </div>
                </div>
            </div>
        </footer>

    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <!-- Bootstrap core JS-->
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="js/scripts.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/simple-datatables@latest" crossorigin="anonymous"></script>
    <script src="js/datatables-simple-demo.js"></script>
    
    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>